apiVersion: v1
kind: Secret
metadata:
  name: super-id-service-secrets
type: Opaque
data:
  SUPER_ID_SERVICE_SUPABASE_URL: SUPER_ID_SERVICE_SUPABASE_URL_BASE64
  SUPER_ID_SERVICE_SUPABASE_ANON_KEY: SUPER_ID_SERVICE_SUPABASE_ANON_KEY_BASE64
  SUPER_ID_SERVICE_SUPABASE_SERVICE_ROLE_KEY: SUPER_ID_SERVICE_SUPABASE_SERVICE_ROLE_KEY_BASE64
  SUPER_ID_SERVICE_M2M_JWT_SECRET_KEY: SUPER_ID_SERVICE_M2M_JWT_SECRET_KEY_BASE64
  SUPER_ID_SERVICE_DATABASE_URL: SUPER_ID_SERVICE_DATABASE_URL_BASE64
